#!/bin/bash

# Define password as a constant
PASSWORD="4z65jKjbw6c8"  # Replace this with the actual password

if [ "$#" -le 0 ]; then
    echo "Usage: $0 <TEAM #>"
    exit 0
fi

ND=$(($1 % 5))
LL=$(($1 + 1))
CM=$LL"q;d"
CL=$(( $(($1 / 5)) * 5))
M0=$(($ND + $CL))
M1=$(( $(( $(($ND + 1)) % 5)) + $CL))
M2=$(( $(( $(($ND + 2)) % 5)) + $CL))
M3=$(( $(( $(($ND + 3)) % 5)) + $CL))
M4=$(( $(( $(($ND + 4)) % 5)) + $CL))

# Open terminals with SSH sessions using the hardcoded password
gnome-terminal -- bash -c "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no netfpga@nf$M0.usc.edu" &
gnome-terminal -- bash -c "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no node$ND@nf$M1.usc.edu" &
gnome-terminal -- bash -c "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no node$ND@nf$M2.usc.edu" &
gnome-terminal -- bash -c "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no node$ND@nf$M3.usc.edu" &
gnome-terminal -- bash -c "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no node$ND@nf$M4.usc.edu" &
